keys:
  # Replace this placeholder recipient with your own before adding real secrets.
  - &dididi_age age1k4tf0fjzhq9wc98hawtep00qgupvxy3shj3axwjyg8updspztugqc66y40
creation_rules:
  - path_regex: secrets/.*\.yaml$
    age: [ *dididi_age ]
